Repository connectomicslab/connectomemapper3, pull requests merged in 2022-02, with the labels that each got.

#148 REF: Load all parcellation scale at once in freeview
  cmp/stages/parcellation/parcellation.py
Labels: refactoring

#147 UPD: Update Freesurfer to 7.2.0
  .circleci/config.yml
  .circleci/tests/expected_outputs/ds-sample_test-01_outputs.txt
  .circleci/tests/expected_outputs/ds-sample_test-02_outputs.txt
  .circleci/tests/expected_outputs/ds-sample_test-03_outputs.txt
  .circleci/tests/expected_outputs/ds-sample_test-04_outputs.txt
  .circleci/tests/expected_outputs/ds-sample_test-05_outputs.txt
  .circleci/tests/expected_outputs/ds-sample_test-06_outputs.txt
  .circleci/tests/expected_outputs/ds-sample_test-07_outputs.txt
  .circleci/tests/expected_outputs/ds-sample_test-08_outputs.txt
  .circleci/tests/expected_outputs/ds-sample_test-09-simg_outputs.txt
  Dockerfile
  cmtklib/bids/io.py
  cmtklib/parcellation.py
  docs/bidsappmanager.rst
  docs/conf.rst
  docs/datalad.rst
  docs/implementation.rst
  docs/outputs.rst
  docs/usage.rst
Labels: maintenance

#141 DOC: Analysis Tutorial
  README.md
  cmp/bidsappmanager/gui/bidsapp.py
  cmp/bidsappmanager/gui/config.py
  cmp/bidsappmanager/gui/globals.py
  cmp/bidsappmanager/gui/principal.py
  cmp/bidsappmanager/gui/qc.py
  cmtklib/data/__init__.py
  cmtklib/data/parcellation/__init__.py
  cmtklib/data/parcellation/lausanne2018/mni-space/atlas-L2018_res-scale1_coords.csv
  cmtklib/data/parcellation/lausanne2018/mni-space/atlas-L2018_res-scale2_coords.csv
  cmtklib/data/parcellation/lausanne2018/mni-space/atlas-L2018_res-scale3_coords.csv
  cmtklib/data/parcellation/lausanne2018/mni-space/atlas-L2018_res-scale4_coords.csv
  cmtklib/data/parcellation/lausanne2018/mni-space/atlas-L2018_res-scale5_coords.csv
  cmtklib/data/parcellation/util.py
  cmtklib/data/parcellation/viz.py
  docs/api_doc.rst
  docs/requirements.txt
  notebooks/analysis_tutorial.ipynb
  notebooks/tutorial_environment.yml
  setup.py
  setup_pypi.py
Labels: enhancement, documentation, Brainhack21!

#82 ENH: EEG pipeline implementation
  .codecov.yml
  .coveragerc
  .gitignore
  cmp/cli/connectomemapper3.py
  cmp/parser.py
  cmp/pipelines/anatomical/anatomical.py
  cmp/pipelines/diffusion/diffusion.py
  cmp/pipelines/functional/eeg.py
  cmp/pipelines/functional/fMRI.py
  cmp/project.py
  cmp/stages/connectome/connectome.py
  cmp/stages/eeg/__init__.py
  cmp/stages/eeg/inverse_solution.py
  cmp/stages/eeg/loader.py
  cmp/stages/eeg/preparer.py
  cmp/stages/segmentation/segmentation.py
  cmtklib/bids/io.py
  cmtklib/config.py
  cmtklib/eeg.py
  cmtklib/interfaces/ants.py
  cmtklib/interfaces/eeg.py
  cmtklib/interfaces/mne.py
  cmtklib/interfaces/pycartool.py
  conda/environment.yml
  conda/environment_macosx.yml
  docker/environment.yml
  docker/requirements.txt
  docs/api_doc.rst
  docs/conf.py
  docs/download.rst
  docs/exampleresults.rst
  docs/notebooks.rst
  docs/notebooks/EEG_pipeline_tutorial.ipynb
  docs/notebooks/EEG_tutorial_environment.yml
  docs/notebooks/EEG_tutorial_utils.py
  docs/notebooks/analysis_tutorial.ipynb
  docs/notebooks/ref_mne_eeg_config.json
  docs/quality.rst
  docs/requirements.txt
  docs/sidebar_version.html
  docs/stages.rst
  run.py
  setup.py
Labels: enhancement
